name = "sub-converter-worker"
main = "src/index.ts"
compatibility_date = "2025-04-21"
compatibility_flags = []
workers_dev = true

routes = [
  { pattern = "sub.cyborgoat.com", custom_domain = true }
]
