name = "sub-converter-worker"
main = "src/index.ts"
compatibility_date = "2025-04-21"
compatibility_flags = []

[env.production]
routes = [
  { pattern = "sub-converter.example.com/*", zone_name = "example.com" }
]
